name: asian_paradise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  sqflite: ^2.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sushi.jpg
    - assets/indian.jpg
    - assets/thai.jpg
    - assets/korean.jpg
    - assets/jiaozi.jpg
    - assets/onigiri.jpg
    - assets/bibimbap.jpg
    - assets/satay.jpg
    - assets/biryani.jpg
    - assets/bun bo hue.jpg
    - assets/char siu.jpg
    - assets/kimchi.jpg
    - assets/dim sum.jpg
    - assets/kimbap.jpg
    - assets/ramen.jpg
    - assets/tteokbokki.jpg


