@startuml
!include_once https://raw.githubusercontent.com/chilit-nl/plantuml-event-modeling/main/event-modeling-lib.iuml

$enableAutoAlias()
$enableAutoSpacing()

' Configure the names of the lanes
$configureWireframeLane(Customer)
$configureWireframeLane(Employee)
$configureWireframeLane(Driver)
$configureEventLane(Order, $context = Order)
$configureEventLane(Feedback, $context = Feedback)

' Provide all elements in order
$wireframe(MenuScreen, Customer)
$view(MenuCategories)
$view(DishDetails)
$command(SelectDish)
$event(DishSelected, Order)
$arrow(MenuCategories, MenuScreen)
$arrow(DishDetails, MenuScreen)

$wireframe(OrderScreen, Customer)
$command(SubmitOrder)
$event(OrderSubmitted, Order)
$view(Orders)
$arrow(Orders, OrderScreen)

$wireframe(EmployeeScreen, Employee)
$command(DispatchOrder)
$event(OrderDispatched, Order)
$view(Orders)
$arrow(Orders, EmployeeScreen)

$wireframe(DriverApp, Driver)
$command(PickUpOrder)
$event(OrderPickedUp, Order)
$view(DeliveryStatus)
$arrow(DeliveryStatus, DriverApp)

$command(CompleteDelivery)
$event(OrderDelivered, Order)
$view(DeliveryStatus)
$arrow(DeliveryStatus, OrderScreen)

$wireframe(FeedbackScreen, Customer)
$command(WriteReview)
$event(ReviewSubmitted, Feedback)
$view(Reviews)
$arrow(Reviews, FeedbackScreen)

' Render the diagram
$renderEventModelingDiagram()
@enduml
