name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List files to debug
      - name: List files
        run: ls -la

      # Step 4: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 5: Build and run containers with Docker Compose
      - name: Build and run containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # Step 6: Shutdown containers after tests
      - name: Shutdown containers
        run: |
          docker compose down

      # Step 7: Publish Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-app:latest my-dockerhub-username/my-app:latest
          docker push my-dockerhub-username/my-app:latest
