name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and run containers with Docker Compose
      - name: Build and run containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up --build -d

      # Step 5: Run tests
      - name: Run tests
        run: |
          docker compose exec <container_name> npm test

      # Step 6: Shutdown containers after tests
      - name: Shutdown containers
        run: |
          docker compose down

      # Step 7: Publish Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-app:latest my-dockerhub-username/my-app:latest
          docker push my-dockerhub-username/my-app:latest
