version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - DB_HOST=db_host
      - DB_PORT=5432

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_service
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
