name: PlantUML Diagrams

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  render_diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Render PlantUML diagrams
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml
          plantuml -o ./output ./diagram.p
